import ListPost from '@/components/ListPost'
import { GetStaticProps, NextPage } from 'next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import Head from 'next/head'
import React from 'react'

const ListPostPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Base i18n Page Route</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <div className={`page`}>
        <ListPost />
      </div>
    </>
  )
}

export const getStaticProps: GetStaticProps = async ({ locale }) => ({
    props: {
      ...(await serverSideTranslations(locale || 'en', [
        'common',
        'layouts/header',
        'layouts/footer',
        'pages/list-post',
      ])),
    },
  })

export default ListPostPage
